apiVersion: v1
kind: Service
metadata:
  name: serpent-service
  namespace: serpent
  labels:
    app: serpent-web
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    name: http
  selector:
    app: serpent-web