name: Build and Deploy Docker Conatiner Image

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

on:
    push:
        branches: [ "main" ]

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          with:
            platforms: linux/amd64,linux/arm64

        - name: Log into registry
          uses: docker/login-action@v2.2.0
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
              images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4.1.1
          with:
            platforms: linux/amd64,linux/arm64
            push: true
            tags: |
                ghcr.io/ckriutz/serpent-bottle:latest
                ghcr.io/ckriutz/serpent-bottle:${{ github.run_number }}
            labels: ${{ steps.meta.outputs.tags }}